"""K5

Revision ID: 1b7f577d343b
Revises: 45f517e3b6de
Create Date: 2025-05-07 14:05:29.016248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7f577d343b'
down_revision: Union[str, None] = '45f517e3b6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profile', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'category_id')
    # ### end Alembic commands ###
