"""Добавлен описание и цена table Product

Revision ID: bc569b12c43b
Revises: e24174f4b864
Create Date: 2025-05-10 16:13:59.730969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc569b12c43b'
down_revision: Union[str, None] = 'e24174f4b864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('Description', sa.Text(), nullable=False))
    op.add_column('product', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    op.drop_column('product', 'Description')
    # ### end Alembic commands ###
