"""K6

Revision ID: e24174f4b864
Revises: 1b7f577d343b
Create Date: 2025-05-07 14:16:44.397823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e24174f4b864'
down_revision: Union[str, None] = '1b7f577d343b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_products',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.drop_constraint('profile_ibfk_2', 'profile', type_='foreignkey')
    op.drop_column('profile', 'category_id')
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('user', 'first_name')
    op.add_column('profile', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('profile_ibfk_2', 'profile', 'category', ['category_id'], ['id'])
    op.drop_table('user_products')
    # ### end Alembic commands ###
